title: cdev-cli documentation
description: A command-line script that facilitates using a docker container to learn C development.
theme: just-the-docs

url: https://matteospanio.github.io/cdev-cli/

aux_links:
  Github Repository: https://github.com/matteospanio/cdev-cli
